---
- hosts: webservers
  become: yes
  become_user: root
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: Loome public_html kataloogi user'ile
      file:
        path=/home/user/public_html
        owner=user
        group=user
        mode=0755
        state=directory

    - name: Lubame userdir mod
      apache2_module: name=userdir state=present

    - name: Apache2 serverile alglaadimine(restart)
      service:
        name: apache2
        state: restarted

    - name: Kopeerime index.html fail USER'ile kodus_public_html kataloogi
      copy:
        src: /var/www/html/index.html
        dest: /home/user/public_html/
        remote_src: yes
        owner: user
        group: user

    - name: user index.html redigeerimine
      lineinfile: dest=/home/user/public_html/index.html regexp="Apache2 Ubuntu Default Page" line="USER1 lehekylg" state=present

    - name: Alglaadimine Apache2
      service:
        name: apache2
        state: restarted